### ISSUE TITLE
how to set min max value in config

### ISSUE THREAD

**Issue by monajafi** [sagiegurari/angular-number-input#1]
Dear Sir
I am trying to set min max value in config through service how should I do that 
any sample will be appreciated

**Comment by sagiegurari** [comment]
Actually, I only planned to have parse/format/validation/link capabilities implemented in the service while min/max/step defined outside.

You can see it at:
https://github.com/sagiegurari/angular-number-input/blob/master/docs/api.md#NumberInputService

I could modify it to allow the service to define those.
If you wish i'll implement that maybe later today/tomorrow.

**Comment by monajafi** [comment]
Hi sir
Thank you very much for your kind attention. I'll appreciate if you
implement that

regards
Mousa

**Comment by sagiegurari** [comment]
you can now set min/max/step via service.
please check it to see if it is working good for you.

**Comment by monajafi** [comment]
Hi sagie
Thanks a lot
Regards
Mousa
