### ISSUE TITLE
Can't handle decimals with a zero

### ISSUE THREAD

**Issue by yesman85** [sagiegurari/angular-number-input#2]
Try the following value on the demo: 10.05. It will return undefined.

**Comment by sagiegurari** [comment]
ya thats because in the demo I set in the html for the first 2 inputs the following:

````html
step="0.5"
````

you can change that to 0.01 for example and it will work.
for example the third input has smaller step and it works.
so its pure configuration based on your needs.

**Comment by yesman85** [comment]
Ah ok you are right! Thanks for the clarification.
