### ISSUE TITLE
השדה מאפשר הקלדת טקסט מדוע ?

### ISSUE THREAD

**Issue by yaronmil** [sagiegurari/angular-number-input#3]
רוצה למנוע הקלדה של כל מה שאינו מספר

**Comment by sagiegurari** [comment]
because you might want text for example you might write a service that allows writing 1M for 1 million or 10$ (like in the example code).

**Comment by yaronmil** [comment]
i was lokking for numbers only constraint.
thank u.

**Comment by yaronmil** [comment]
i was finlay adding a parser to directive ,that did the trick ,
but at the beging that didnt work (on ie11) untill i changed the input type from numeric to text
thank you for your assistant !!
